@base_url = http://127.0.0.1:3000
@url = {{base_url}}/api/users

GET {{url}}

###

POST {{url}}
Content-Type: application/json

{
	"name": "Test 1",
	"email": "test12345@test.com",
	"password": "test123",
	"goole": true,
	"role": "ADMIN"
}

###

PUT {{url}}/63e3cbcbd80822d2f2ac4b33
Content-Type: application/json

{
  "name": "Test 1",
	"email": "test1@test.com",
	"password": "test123",
	"goole": true,
  "role": "ADMIN",
  "status": true
}

###

PUT {{url}}/63e3cbcbd80822d2f2ac4b33
Content-Type: application/json

{
  "status": true
}

###

DELETE {{url}}/63e3cbcbd80822d2f2ac4b33 HTTP/1.1
Content-Type: application/json

###

DELETE {{url}}/63e6acd0a35e13605c069517 HTTP/1.1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2UzY2JjYmQ4MDgyMmQyZjJhYzRiMzMiLCJpYXQiOjE2NzYwNjIyMDEsImV4cCI6MTY3NjA3NjYwMX0.ArQ3qxamXLE7177Q1GYw9VA7--BkINy23g3uMZtjccY
